import {defineArrayMember, defineField, defineType} from 'sanity'

export const homePageType = defineType({
  name: 'homePage',
  title: '首页',
  type: 'document',
  groups: [
    {name: 'general', title: '基础信息'},
    {name: 'hero', title: '首屏 Hero'},
    {name: 'content', title: '首页模块'},
    {name: 'seo', title: 'SEO 设置'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: '页面标题',
      type: 'string',
      group: 'general',
      description: '用于首页元信息兜底和 Studio 内部识别。',
      validation: (rule) => rule.required(),
      initialValue: 'Prophetchef Homepage',
    }),
    defineField({
      name: 'hero',
      title: '首屏 Hero',
      type: 'object',
      group: 'hero',
      fields: [
        {name: 'eyebrow', title: '眉标题', type: 'string'},
        {name: 'title', title: '主标题', type: 'string'},
        {name: 'description', title: '说明文案', type: 'text', rows: 3},
        {
          name: 'backgroundImage',
          title: '背景图',
          type: 'image',
          options: {hotspot: true},
          fields: [{name: 'alt', title: '图片替代文字', type: 'string'}],
        },
        {name: 'primaryCta', title: '主按钮', type: 'ctaButton'},
        {name: 'secondaryCta', title: '次按钮', type: 'ctaButton'},
        {
          name: 'trustTags',
          title: '信任标签',
          type: 'array',
          description: '首屏中展示的简短标签，最多 6 个。',
          of: [defineArrayMember({type: 'string'})],
          validation: (rule) => rule.max(6),
        },
        {
          name: 'proofItems',
          title: '数据背书',
          type: 'array',
          description: '首屏展示的数字背书，最多 4 个。建议同时填写数值和标签，例如 20+ / Years Mfg.',
          of: [defineArrayMember({type: 'statItem'})],
          validation: (rule) => rule.max(4),
        },
      ],
    }),
    defineField({
      name: 'categorySection',
      title: '产品分类区标题',
      type: 'sectionHeader',
      group: 'content',
    }),
    defineField({
      name: 'featuredCategories',
      title: '首页精选分类',
      type: 'array',
      group: 'content',
      description: '最多选择 6 个；为空时前台可按默认规则展示。',
      of: [{type: 'reference', to: [{type: 'category'}]}],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: 'featuredProductsSection',
      title: '精选产品区标题',
      type: 'sectionHeader',
      group: 'content',
    }),
    defineField({
      name: 'featuredProducts',
      title: '首页精选产品',
      type: 'array',
      group: 'content',
      description: '最多选择 8 个，用于首页重点推荐。',
      of: [{type: 'reference', to: [{type: 'product'}]}],
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: 'factoryPreview',
      title: '工厂预览模块',
      type: 'mediaTextSection',
      group: 'content',
    }),
    defineField({
      name: 'applicationsPreviewSection',
      title: '应用场景区标题',
      type: 'sectionHeader',
      group: 'content',
    }),
    defineField({
      name: 'featuredApplications',
      title: '首页精选应用场景',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'application'}]})],
      validation: (rule) => rule.max(6),
    }),
    defineField({
      name: 'certificatesPreviewSection',
      title: '认证资质区标题',
      type: 'sectionHeader',
      group: 'content',
    }),
    defineField({
      name: 'featuredCertificates',
      title: '首页精选认证',
      type: 'array',
      group: 'content',
      of: [defineArrayMember({type: 'reference', to: [{type: 'certificate'}]})],
      validation: (rule) => rule.max(8),
    }),
    defineField({
      name: 'newsSection',
      title: '新闻区块',
      type: 'object',
      group: 'content',
      fields: [
        {name: 'title', title: '标题', type: 'string'},
        {name: 'subtitle', title: '副标题', type: 'string'},
        {
          name: 'articles',
          title: '手动选择文章（可选）',
          description: '留空时自动展示最新新闻。',
          type: 'array',
          of: [{type: 'reference', to: [{type: 'newsArticle'}]}],
        },
      ],
    }),
    defineField({
      name: 'seo',
      title: 'SEO 设置',
      type: 'seo',
      group: 'seo',
    }),
  ],
  preview: {
    prepare() {
      return {
        title: '首页',
        subtitle: '首屏、精选产品、工厂、应用、认证和新闻模块',
      }
    },
  },
})
