/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
  openGraphTitle?: string;
  openGraphDescription?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  legalName?: string;
  description?: string;
  siteUrl?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  contactInfo?: {
    email?: string;
    phone?: string;
    whatsapp?: string;
    address?: string;
  };
  mainNavigation?: Array<{
    _key: string;
  } & NavigationLink>;
  footerProductLinks?: Array<{
    _key: string;
  } & NavigationLink>;
  footerCompanyLinks?: Array<{
    _key: string;
  } & NavigationLink>;
  footerBadges?: Array<{
    _key: string;
  } & StatItem>;
  socialLinks?: Array<{
    platform?: string;
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  globalCta?: GlobalCta;
  globalSeo?: Seo;
};

export type GlobalCta = {
  _type: "globalCta";
  eyebrow?: string;
  title?: string;
  description?: string;
  primaryCta?: CtaButton;
  whatsappText?: string;
  whatsappMessage?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: PageHero;
  eyebrow?: string;
  heading?: string;
  lead?: string;
  seo?: Seo;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow?: string;
  title?: string;
  description?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  primaryCta?: CtaButton;
  secondaryCta?: CtaButton;
};

export type CertificateReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "certificate";
};

export type CertificatesPage = {
  _id: string;
  _type: "certificatesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: PageHero;
  certificatesHeader?: SectionHeader;
  featuredCertificates?: Array<{
    _key: string;
  } & CertificateReference>;
  processHeader?: SectionHeader;
  processSteps?: Array<string>;
  documentationCta?: {
    title?: string;
    description?: string;
    button?: CtaButton;
  };
  seo?: Seo;
};

export type CtaButton = {
  _type: "ctaButton";
  text?: string;
  href?: string;
};

export type SectionHeader = {
  _type: "sectionHeader";
  eyebrow?: string;
  title?: string;
  description?: string;
  cta?: CtaButton;
};

export type ApplicationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "application";
};

export type ApplicationsPage = {
  _id: string;
  _type: "applicationsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: PageHero;
  gridHeader?: SectionHeader;
  featuredApplications?: Array<{
    _key: string;
  } & ApplicationReference>;
  solutionsHeader?: SectionHeader;
  solutionDetails?: Array<{
    title?: string;
    painPoints?: string;
    recommendedEquipment?: string;
    benefits?: string;
    cta?: CtaButton;
    _type: "solutionDetail";
    _key: string;
  }>;
  seo?: Seo;
};

export type FactoryPage = {
  _id: string;
  _type: "factoryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: PageHero;
  overview?: MediaTextSection;
  stats?: Array<{
    _key: string;
  } & StatItem>;
  productionHeader?: SectionHeader;
  productionSteps?: Array<{
    _key: string;
  } & TextCard>;
  teamHeader?: SectionHeader;
  teamItems?: Array<{
    _key: string;
  } & TextCard>;
  marketsHeader?: SectionHeader;
  exportMarkets?: Array<{
    _key: string;
  } & StatItem>;
  seo?: Seo;
};

export type MediaTextSection = {
  _type: "mediaTextSection";
  eyebrow?: string;
  title?: string;
  paragraphs?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bullets?: Array<string>;
  cta?: CtaButton;
};

export type NewsPage = {
  _id: string;
  _type: "newsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: PageHero;
  seo?: Seo;
};

export type ProductsPage = {
  _id: string;
  _type: "productsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: PageHero;
  metrics?: Array<{
    _key: string;
  } & StatItem>;
  seo?: Seo;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type NewsArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsArticle";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    backgroundImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    primaryCta?: CtaButton;
    secondaryCta?: CtaButton;
    trustTags?: Array<string>;
    proofItems?: Array<{
      _key: string;
    } & StatItem>;
  };
  categorySection?: SectionHeader;
  featuredCategories?: Array<{
    _key: string;
  } & CategoryReference>;
  featuredProductsSection?: SectionHeader;
  featuredProducts?: Array<{
    _key: string;
  } & ProductReference>;
  factoryPreview?: MediaTextSection;
  applicationsPreviewSection?: SectionHeader;
  featuredApplications?: Array<{
    _key: string;
  } & ApplicationReference>;
  certificatesPreviewSection?: SectionHeader;
  featuredCertificates?: Array<{
    _key: string;
  } & CertificateReference>;
  newsSection?: {
    title?: string;
    subtitle?: string;
    articles?: Array<{
      _key: string;
    } & NewsArticleReference>;
  };
  seo?: Seo;
};

export type NewsCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "newsCategory";
};

export type NewsArticle = {
  _id: string;
  _type: "newsArticle";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  publishedAt?: string;
  category?: NewsCategoryReference;
  tags?: Array<string>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  isArchived?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type NewsCategory = {
  _id: string;
  _type: "newsCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  orderRank?: number;
};

export type Certificate = {
  _id: string;
  _type: "certificate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shortLabel?: string;
  description?: string;
  icon?: "badgeCheck" | "clipboardCheck" | "fileCheck" | "plug" | "recycle" | "shieldCheck";
  orderRank?: number;
};

export type Application = {
  _id: string;
  _type: "application";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  recommended?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  quoteProductName?: string;
  orderRank?: number;
  seo?: Seo;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: CategoryReference;
  description?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  features?: Array<{
    _key: string;
  } & ProductFeature>;
  specifications?: Array<{
    _key: string;
  } & ProductSpecification>;
  tags?: Array<string>;
  modelCode?: string;
  faqs?: Array<{
    _key: string;
  } & FaqItem>;
  isArchived?: boolean;
  orderRank?: number;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  orderRank?: number;
  seo?: Seo;
};

export type ProductSpecification = {
  _type: "productSpecification";
  label?: string;
  value?: string;
};

export type ProductFeature = {
  _type: "productFeature";
  title?: string;
  description?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type NavigationLink = {
  _type: "navigationLink";
  label?: string;
  href?: string;
};

export type TextCard = {
  _type: "textCard";
  title?: string;
  description?: string;
  icon?: "badgeCheck" | "building" | "calendar" | "checkCircle" | "clipboardCheck" | "clock" | "compass" | "factory" | "fileCheck" | "flask" | "globe" | "headset" | "landmark" | "mailCheck" | "map" | "mapPin" | "maximize" | "plane" | "plug" | "recycle" | "scissors" | "settings" | "shieldCheck" | "ship" | "sparkles" | "users" | "waves" | "wrench" | "zap";
};

export type StatItem = {
  _type: "statItem";
  value?: string;
  label?: string;
  icon?: "badgeCheck" | "building" | "calendar" | "checkCircle" | "clipboardCheck" | "clock" | "compass" | "factory" | "fileCheck" | "flask" | "globe" | "headset" | "landmark" | "mailCheck" | "map" | "mapPin" | "maximize" | "plane" | "plug" | "recycle" | "scissors" | "settings" | "shieldCheck" | "ship" | "sparkles" | "users" | "waves" | "wrench" | "zap";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | Seo | SiteSettings | GlobalCta | SanityImageCrop | SanityImageHotspot | ContactPage | PageHero | CertificateReference | CertificatesPage | CtaButton | SectionHeader | ApplicationReference | ApplicationsPage | FactoryPage | MediaTextSection | NewsPage | ProductsPage | CategoryReference | ProductReference | NewsArticleReference | HomePage | NewsCategoryReference | NewsArticle | Slug | NewsCategory | Certificate | Application | Product | Category | ProductSpecification | ProductFeature | FaqItem | NavigationLink | TextCard | StatItem | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

