import {
  BadgeCheck,
  Building2,
  Calendar,
  CheckCircle2,
  ClipboardCheck,
  Clock3,
  Compass,
  Factory,
  FileCheck,
  FlaskConical,
  Globe2,
  Headset,
  Landmark,
  MailCheck,
  Map,
  MapPinned,
  Maximize,
  Plane,
  PlugZap,
  Recycle,
  Scissors,
  Settings,
  ShieldCheck,
  Ship,
  Sparkles,
  Users,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  badgeCheck: BadgeCheck,
  building: Building2,
  calendar: Calendar,
  checkCircle: CheckCircle2,
  clipboardCheck: ClipboardCheck,
  clock: Clock3,
  compass: Compass,
  factory: Factory,
  fileCheck: FileCheck,
  flask: FlaskConical,
  globe: Globe2,
  headset: Headset,
  landmark: Landmark,
  mailCheck: MailCheck,
  map: Map,
  mapPin: MapPinned,
  maximize: Maximize,
  plane: Plane,
  plug: PlugZap,
  recycle: Recycle,
  scissors: Scissors,
  settings: Settings,
  shieldCheck: ShieldCheck,
  ship: Ship,
  sparkles: Sparkles,
  users: Users,
  waves: Waves,
  wrench: Wrench,
  zap: Zap,
};

export function getIcon(name: string | undefined, fallback: LucideIcon = BadgeCheck) {
  return name ? iconMap[name] ?? fallback : fallback;
}
